### ISSUE TITLE
Unable to run app

### ISSUE THREAD

**Issue by RizwanaDesai** [mainframecomputer/fullmoon-ios#21] opened 2024-11-14 08:40 UTC
I'm trying to run the app but encountered an error, and haven't been able to find a fix.

<img width="900" alt="Screenshot 2024-11-14 at 1 48 52 PM" src="https://github.com/user-attachments/assets/872c565c-1d30-4e51-96f7-63b67df74453">

I tried setting` let prompt = modelConfiguration.defaultPrompt` and ran the app again, but it crashed. I've attached a screenshot showing where the crash occurred.
<img width="1164" alt="Screenshot 2024-11-14 at 1 48 08 PM" src="https://github.com/user-attachments/assets/57847ba8-29b9-4f07-94aa-ecebcf3c046c">

Additional Context
Device:  iOS Simulator 18, 17.4
Xcode Version: Xcode 16
Fixed Info.plist Error as well, with the help of one of the open issue answer's.

I would really appreciate any help.

**Comment by jordansinger** [comment] 2024-11-23 15:16
if you pull the latest main branch it should be fixed!

**Comment by bartaxyz** [comment] 2024-12-01 15:15
The model configuration has been fixed. The second issue, however, still exists.

It's building fine on a real device, the issue is only when building for the iOS Simulator. So, the way around this is to just use a real device.

<img width="827" alt="Screenshot 2024-12-01 at 15 59 56" src="https://github.com/user-attachments/assets/22ae0da1-5993-4f43-871a-d42e94b57343">

**Comment by RizwanaDesai** [comment] 2024-12-06 17:22
Latest Pull worked. Thanks @jordansinger

**Closed as completed** 2024-12-06 17:23 UTC
